version: '2.1'
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.3
jobs:
  build:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            npm install
      - run:
          name: "Run Test Suite"
          command: |
            npm test
  build-and-push-image:
    executor: gcp-gcr/default
    environment:
      DOCKER_TAG:
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - run:
          command: export DOCKER_TAG=$(git show -s --date=format:'%Y-%m-%d' --format=%cd-%h) && echo "export DOCKER_TAG=\"$DOCKER_TAG\"" >> "$BASH_ENV"
      - gcp-gcr/build-and-push-image:
          image: scamp-js
          tag: ${DOCKER_TAG}
workflows:
  commit:
    jobs:
      - build
      - build-and-push-image:
          context:
            - gcp-prod
          dependencies:
            - build
          filters:
            branches:
              only:
                - master
