#!/bin/sh

set -e
service="$1"

mkdir -p "$SCAMP_CONFIG_DIR/services"

#touch "$SCAMP_CONFIG_DIR/scamp.conf"
touch "$SCAMP_CONFIG_DIR/authorized_services"
touch "/tmp/scamp_discovery_cache"
mkdir -p /tmp/scamp_running_services/

[ -f "$SCAMP_CONFIG_DIR/services/$service.key" ] && exit 0

openssl req -new -nodes -subj "/CN=$hostname $(echo $service | sed 's|/|:|g')" -x509 -days 3650 \
        -newkey rsa:4096 -out "$SCAMP_CONFIG_DIR/services/$service.crt" -keyout "$SCAMP_CONFIG_DIR/services/$service.key"
